# Generated by Django 5.2 on 2025-09-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_tect_choice_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='questin',
            new_name='question',
        ),
    ]
